---
- name: apt install
  apt: name={{item}} update_cache=yes state=present
  with_items:
    - git
    - i3
    - emacs
    - workrave
    - silversearcher-ag
    - firefox
    # - chrome
    - terminator
    - dolphin
    - kmix
    - uzbl
    - ghc
    - python-pip
    - python3
    - python3-pip

- name: Download Chrome
  get_url:
    url: "{{ chrome_download_url }}"
    dest: "{{ download_dir }}/{{ chrome_download_url | basename }}"

- name: Install Chrome
  apt:
    deb: "{{ download_dir }}/{{ chrome_download_url | basename }}"
    state: present

- name: Install python packages
  pip: name={{ item }}
  with_items:
    - youtube-dl
    - virtualenvwrapper
