---
- name: apt upgrade installed packages
  apt:
    update_cache: yes
    state: present
    upgrade: dist

- name: apt install
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  with_items:
    - git
    - gitk
    - i3
    - emacs
    - workrave
    - silversearcher-ag
    - firefox
    # - chrome
    - terminator
    - dolphin
    - kmix
    # - uzbl
    - jq
    - ghc
    - python-pip
    - python3
    - python3-pip
    - ksysguard
    - kate
    - kwrite
    - kdesudo
    - openssh-server
    - exuberant-ctags
    - isympy
    - python-sympy
    - python3-sympy
    - pavucontrol
    - gwenview
    - meld
    - fish

- name: Download Chrome
  get_url:
    url: "{{ chrome_download_url }}"
    dest: "{{ download_dir }}/{{ chrome_download_url | basename }}"
  tags:
    - chrome

- name: Install Chrome
  apt:
    deb: "{{ download_dir }}/{{ chrome_download_url | basename }}"
    state: present
  tags:
    - chrome

- name: Install python packages
  pip: name={{ item }}
  with_items:
    - youtube-dl
    - virtualenvwrapper
