---
- name: apt install
  apt:
    name:
      - git
      - gitk
      - i3
      - emacs
      - workrave
      - silversearcher-ag
      - firefox
      # - chrome
      - terminator
      - dolphin
      - kmix
      # - uzbl
      - jq
      - ghc
      # - python-pip
      - python3
      - python3-pip
      - python3-venv
      - pipx
      - ksysguard
      - kate
      - kwrite
      # - kdesudo
      - openssh-server
      - exuberant-ctags
      - pavucontrol
      - gwenview
      - meld
      # - fish
      - vlc
      # - kvirc
      # - w3m
      
      ### Python build dependencies (for pyenv):
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    update_cache: yes
    state: present

- name: apt upgrade installed packages
  apt:
    update_cache: yes
    state: present
    upgrade: dist

- name: Download Chrome
  get_url:
    url: "{{ chrome_download_url }}"
    dest: "{{ download_dir }}/{{ chrome_download_url | basename }}"
  tags:
    - chrome

- name: Install Chrome
  apt:
    deb: "{{ download_dir }}/{{ chrome_download_url | basename }}"
    state: present
  tags:
    - chrome
