---
# Various python packages
- name: Install python packages
  command:
    cmd: >-
      pipx install {{ item.name }}
      {% if item.include_deps %} --include-deps {% endif %}
    creates: "{{ local_bin_dir }}/{{ item.command }}"
  with_items:
    - name: youtube-dl
      command: youtube-dl
      include_deps: no
    - name: virtualenvwrapper
      command: virtualenvwrapper.sh
      include_deps: yes
    - name: sympy
      command: isympy
      include_deps: no
    - name: pyan3
      command: pyan3
      include_deps: no
    - name: jupyter
      command: jupyter
      include_deps: yes
    # - flake8
    # - black
    # - mypy

- name: Install IPython for sympy
  command:
    cmd: pipx runpip sympy install IPython
    creates: "{{ local_dir }}/pipx/venvs/sympy/bin/ipython"

# Anki
- name: Download Anki
  get_url:
    url: "{{ anki_download_url }}"
    # We specify the exact download location so we only download if it's
    # not already there
    dest: "{{ download_dir }}/{{anki_download_url | basename}}"

- name: Unarchive Anki
  unarchive:
    src: "{{ download_dir }}/{{anki_download_url | basename }}"
    dest: "{{ local_bin_dir }}"
    copy: no
    creates: "{{ local_bin_dir }}/{{ anki_unarchive_dir }}/bin/anki"

- name: Create symlink to Anki
  file:
    state: link
    src: "{{ local_bin_dir }}/{{ anki_unarchive_dir }}/bin/Anki"
    path: "{{ local_bin_dir }}/{{ item }}"
  with_items:
    - anki
    - Anki


# Node.js
- name: Download Node.js stable
  get_url:
    url: "{{ node_download_url }}"
    # We specify the exact download location so we only download if it's
    # not already there
    dest: "{{ download_dir }}/{{ node_download_url | basename}}"

- name: Unarchive Node.js
  unarchive:
    src: "{{ download_dir }}/{{ node_download_url | basename }}"
    dest: "{{ local_bin_dir }}"
    copy: no
    creates: "{{ local_bin_dir }}/{{ node_unarchive_dir }}/bin/node"

- name: Create symlinks to node and npm
  file:
    state: link
    path: "{{ local_bin_dir }}/{{ item }}"
    src: "{{ local_bin_dir }}/{{ node_unarchive_dir }}/bin/{{ item }}"
  with_items:
    - node
    - npm

# pyenv
- name: Install pyenv
  git:
    dest: "{{ home_dir }}/.pyenv"
    repo: git@github.com:pyenv/pyenv.git
    clone: yes
    update: yes
    accept_hostkey: yes

- name: Dynamic bash extension for pyenv
  shell:
    # cd ~/.pyenv && src/configure && make -C src
    cmd: src/configure && make -C src
    chdir: "{{ home_dir }}/.pyenv"
  ignore_errors: yes

