---
- name: Clone pytagtime
  git:
    dest: "{{ src_dir }}/pytagtime"
    accept_hostkey: yes
    repo: "{{ pytagtime_repo_url }}"
  notify:
    - Restart pytagtime

- name: Create .pytagtimerc
  template:
    dest: "{{ home_dir }}/.pytagtimerc"
    src: pytagtimerc.py
  notify:
    - Restart pytagtime

- name: Install supervisord
  become: yes
  apt: name=supervisor state=present update_cache=yes

- name: Install pytagtime supervisor config
  become: yes
  template:
    dest: "{{ supervisor_conf_dir }}/pytagtime.conf"
    src: pytagtime.conf
  notify:
    - Restart pytagtime

- name: Add cron job to notify if editing tagtime
  become: no
  cron:
    state: present
    user: "{{ ansible_user }}"
    job: >-
      pgrep -f $(echo GntGvzr | tr a-zA-Z n-za-mN-ZA-M) > /dev/null &&
      notify-send -t 60000 tagtime 'Waiting for tagtime'
