---
- name: Clone pytagtime
  git:
    dest: "{{ src_dir }}/pytagtime"
    accept_hostkey: yes
    repo: "{{ pytagtime_repo_url }}"
  notify:
    - Restart pytagtime

- name: Create .pytagtimerc
  template:
    dest: "{{ home_dir }}/.pytagtimerc"
    src: pytagtimerc.py
  notify:
    - Restart pytagtime

- name: Create systemd service file
  template:
    src: pytagtime.service
    dest: "{{ systemd_service_dir }}/pytagtime.service"
    trim_blocks: yes
    lstrip_blocks: yes
  become: yes
  become_user: root
  notify:
    - Restart pytagtime

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  become_user: root

- name: Enable pytagtime systemd unit
  systemd:
    name: pytagtime.service
    enabled: yes
  become: yes
  become_user: root

# - name: Install supervisord
#   become: yes
#   apt: name=supervisor state=present update_cache=yes

# - name: Install pytagtime supervisor config
#   become: yes
#   template:
#     dest: "{{ supervisor_conf_dir }}/pytagtime.conf"
#     src: pytagtime.conf
#   notify:
#     - Restart pytagtime

- name: Add cron job to notify if editing tagtime
  become: no
  cron:
    name: Check tagtime editing
    state: present
    user: "{{ ansible_user_id }}"
    job: >-
      pgrep -f $(echo GntGvzr | tr a-zA-Z n-za-mN-ZA-M) > /dev/null &&
      notify-send -t 60000 tagtime 'Waiting for tagtime'
