#!/bin/bash

basedir=$(dirname $(readlink -f $0))
src=$basedir/home/$1
dst=$HOME/$1

if [ -e $dst ]
then
   read -p "File $dst exists, are you sure you want to install? " -n 1 -r reply
   echo
   if [ $reply != "y" ]
   then
       exit 1
   fi
fi

mkdir -p $(dirname $dst)
ln -sf $src $dst
