---
- name: Download Node.js stable
  get_url:
    url: "{{ node_download_url }}"
    # We specify the exact download location so we only download if it's
    # not already there
    dest: "{{ download_dir }}/{{ node_download_url | basename}}"

- name: Unarchive Node.js
  unarchive:
    src: "{{ download_dir }}/{{ node_download_url | basename }}"
    dest: "{{ bin_dir }}"
    copy: no
    creates: "{{ bin_dir }}/{{ node_unarchive_dir }}/bin/node"

- name: Create symlinks to node and npm
  file:
    state: link
    path: "{{ bin_dir }}/{{ item }}"
    src: "{{ bin_dir }}/{{ node_unarchive_dir }}/bin/{{ item }}"
  with_items:
    - node
    - npm
