---
- name: Ensure directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - "{{ download_dir }}"
    - "{{ bin_dir }}"
    - "{{ local_bin_dir }}"
    - "{{ src_dir }}"
    - "{{ home_dir }}/.bash_completion.d"
    - "{{ media_dir }}"
    - "{{ media_src_dir }}"
