---
- name: Ensure directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - "{{ download_dir }}"
    - "{{ bin_dir }}"
    - "{{ local_bin_dir }}"
    - "{{ src_dir }}"
    - "{{ home_dir }}/.bash_completion.d"
