---
- name: Download Anki
  get_url:
    url: "{{ anki_download_url }}"
    # We specify the exact download location so we only download if it's
    # not already there
    dest: "{{ download_dir }}/{{anki_download_url | basename}}"

- name: Unarchive Anki
  unarchive:
    src: "{{ download_dir }}/{{anki_download_url | basename }}"
    dest: "{{ bin_dir }}"
    copy: no
    creates: "{{ bin_dir }}/{{ anki_unarchive_dir }}/bin/anki"

- name: Create symlink to Anki
  file:
    state: link
    path: "{{ bin_dir }}/anki"
    src: "{{ bin_dir }}/{{ anki_unarchive_dir }}/bin/anki"
