home_dir: "{{ ansible_user_dir }}"
download_dir: "{{ home_dir }}/Downloads"
bin_dir: "{{ home_dir }}/bin"
local_bin_dir: "{{ home_dir }}/.local/bin"
src_dir: "{{ home_dir }}/src"
media_dir: "{{ home_dir }}/media"
media_src_dir: "{{ home_dir }}/media/src"
