---
- name: Add DISPLAY environment variable to the crontab
  tags:
    - crontab
  cron:
    env: yes
    name: DISPLAY
    value: ":0"

- name: Add microbreak reminder cron job
  tags:
    - crontab
  cron:
    name: microbreak reminder
    state: present
    user: "{{ ansible_user }}"
    job: DISPLAY=:0 notify-send microbreak
    minute: "*/9"
